<a href="https://colab.research.google.com/github/LiaDahlia/Pratikum-Machine-Learning/blob/main/Pratikum1_Naive_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Tentukan Dataset
Action1=['Punch','Punch','Kick','Punch','Special','Punch','Kick','Special','Kick','Kick','Special','Special']
Action2=['Punch','Kick','Punch','Special','Punch','Kick','Special','Punch','Kick','Kick','Punch','Kick']
Action3=['Kick','Punch','Special','Punch','Kick','Special','Punch','Kick','Kick','Punch','Punch','Special']
Action4=['Punch','Special','Punch','Kick','Special','Punch','Kick','Kick','Punch','Special','Punch','Kick']

In [ ]:
#Import LabelEncoder
from sklearn import preprocessing
#creating labelEncoder
label = preprocessing.LabelEncoder()
#Convert label string ke numbers
Action1_encoded=label.fit_transform(Action1)
print (Action1_encoded) #0 Kick 1 Punch 2 Special

[1 1 0 1 2 1 0 2 0 0 2 2]


In [ ]:
#Import LabelEncoder
from sklearn import preprocessing
#creating labelEncoder
label = preprocessing.LabelEncoder()
#Convert label string ke numbers
Action2_encoded=label.fit_transform(Action2)
print (Action2_encoded) #0 Kick 1 Punch 2 Special

[1 0 1 2 1 0 2 1 0 0 1 0]


In [ ]:
#Import LabelEncoder
from sklearn import preprocessing
#creating labelEncoder
label = preprocessing.LabelEncoder()
#Convert label string ke numbers
Action3_encoded=label.fit_transform(Action3)
print (Action3_encoded) #0 Kick 1 Punch 2 Special

Action4_encoded=label.fit_transform(Action4)
print (Action4_encoded) #0 Kick 1 Punch 2 Special

[0 1 2 1 0 2 1 0 0 1 1 2]
[1 2 1 0 2 1 0 0 1 2 1 0]


In [ ]:
print ("Action 1:",Action1_encoded)
print ("Action 2:",Action2_encoded)
print ("Action 3:",Action3_encoded)
print ("Action 4:",Action4_encoded) #class

Action 1: [1 1 0 1 2 1 0 2 0 0 2 2]
Action 2: [1 0 1 2 1 0 2 1 0 0 1 0]
Action 3: [0 1 2 1 0 2 1 0 0 1 1 2]
Action 4: [1 2 1 0 2 1 0 0 1 2 1 0]


In [ ]:
#Combining fitur-fitur yang ada
features=zip(Action1_encoded,Action2_encoded,Action3_encoded)
features=list(features)
print (tuple(features))

((1, 1, 0), (1, 0, 1), (0, 1, 2), (1, 2, 1), (2, 1, 0), (1, 0, 2), (0, 2, 1), (2, 1, 0), (0, 0, 0), (0, 0, 1), (2, 1, 1), (2, 0, 2))


In [ ]:
#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Panggil Gaussian Classifier
model = GaussianNB()

#Train model untuk data training
model.fit(features,Action4)
#Model.fit(features,label.reshape(-1,1))

#Peridiction Output
predicted = model.predict([[0,1,1]]) #0 Kick 1 Punch 1 Punch
print ("Hasil Perdiksi:", predicted)

Hasil Perdiksi: ['Punch']
